### ISSUE TITLE
Using Python: "ImportError: ... undefinded symbol .. " finufftpy

### ISSUE THREAD

**Issue by rbrook** [flatironinstitute/finufft#41]
When installing finufftpy, I can't import it.
My command: 
> python -c "import finufftpy"

Output:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/rbrook/.local/share/virtualenvs/myenv/lib/python3.6/site-packages/finufftpy/`__init__`.py", line 23, in <module>
>     from finufftpy._interfaces import nufft1d1,nufft1d2,nufft1d3,nufft2d1,nufft2d1many,nufft2d2,nufft2d2many,nufft2d3,nufft3d1,nufft3d2,nufft3d3
>   File "/home/rbrook/.local/share/virtualenvs/myenv/lib/python3.6/site-packages/finufftpy/_interfaces.py", line 12, in <module>
>     import finufftpy_cpp
> ImportError: /home/rbrook/.local/share/virtualenvs/myenv/lib/python3.6/site-packages/finufftpy_cpp.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z10finufft3d3lPdS_S_PSt7complexIdEidlS_S_S_S2_10nufft_opts

My system:
Ubuntu 16.04/18.04
I compiled FFTW3 from source (for both 3.3.7/3.3.8)

Any idea?

**Comment by ludvigak** [comment]
I can reproduce this error as follows:
```
> git clean -f
Removing contrib/legendre_rule_fast.o
Removing finufftpy/__init__.pyc
Removing finufftpy/_interfaces.pyc
Removing fortran/finufft_f.o
Removing lib-static/libfinufft.a
Removing lib/libfinufft.so
Removing src/common.o
Removing src/dirft1d.o
Removing src/dirft2d.o
Removing src/dirft3d.o
Removing src/finufft1d.o
Removing src/finufft2d.o
Removing src/finufft3d.o
Removing src/finufft_c.o
Removing src/spreadinterp.o
Removing src/utils.o
> pip install .
Processing /home/ludvigak/Dropbox/sfu-workspace/finufft
Requirement already satisfied: numpy in /home/ludvigak/anaconda2/lib/python2.7/site-packages (from finufftpy==1.0.1) (1.15.1)
Requirement already satisfied: pybind11>=2.2 in /home/ludvigak/anaconda2/lib/python2.7/site-packages (from finufftpy==1.0.1) (2.2.4)
Building wheels for collected packages: finufftpy
  Running setup.py bdist_wheel for finufftpy ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-L5wdCO/wheels/b0/c6/54/bcdfb5074f313de4358eedbd1ad17e67ebd5aa7c0a2c1876aa
Successfully built finufftpy
Installing collected packages: finufftpy
  Found existing installation: finufftpy 1.0.1
    Uninstalling finufftpy-1.0.1:
      Successfully uninstalled finufftpy-1.0.1
Successfully installed finufftpy-1.0.1
> python -c 'import finufftpy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "finufftpy/__init__.py", line 23, in <module>
    from finufftpy._interfaces import nufft1d1,nufft1d2,nufft1d3,nufft2d1,nufft2d1many,nufft2d2,nufft2d2many,nufft2d3,nufft3d1,nufft3d2,nufft3d3
  File "finufftpy/_interfaces.py", line 12, in <module>
    import finufftpy_cpp
ImportError: /home/ludvigak/anaconda2/lib/python2.7/site-packages/finufftpy_cpp.so: undefined symbol: _Z14finufft2d2manyilPdS_PSt7complexIdEidllS2_10nufft_opts
> 
```

To fix this, make sure you build the library before install the Python lib:

```
> make lib
g++ -c -fPIC -O3 -funroll-loops -march=native -I src -fopenmp -DNEED_EXTERN_C -fopenmp src/spreadinterp.cpp -o src/spreadinterp.o
g++ -c -fPIC -O3 -funroll-loops -march=native -I src -fopenmp -DNEED_EXTERN_C -fopenmp src/utils.cpp -o src/utils.o
g++ -fPIC -O3 -funroll-loops -march=native -I src -fopenmp -DNEED_EXTERN_C -fopenmp   -c -o src/finufft1d.o src/finufft1d.cpp
g++ -fPIC -O3 -funroll-loops -march=native -I src -fopenmp -DNEED_EXTERN_C -fopenmp   -c -o src/finufft2d.o src/finufft2d.cpp
g++ -fPIC -O3 -funroll-loops -march=native -I src -fopenmp -DNEED_EXTERN_C -fopenmp   -c -o src/finufft3d.o src/finufft3d.cpp
g++ -fPIC -O3 -funroll-loops -march=native -I src -fopenmp -DNEED_EXTERN_C -fopenmp   -c -o src/dirft1d.o src/dirft1d.cpp
g++ -fPIC -O3 -funroll-loops -march=native -I src -fopenmp -DNEED_EXTERN_C -fopenmp   -c -o src/dirft2d.o src/dirft2d.cpp
g++ -fPIC -O3 -funroll-loops -march=native -I src -fopenmp -DNEED_EXTERN_C -fopenmp   -c -o src/dirft3d.o src/dirft3d.cpp
g++ -c -fPIC -O3 -funroll-loops -march=native -I src -fopenmp -DNEED_EXTERN_C -fopenmp src/common.cpp -o src/common.o
gcc -c -fPIC -O3 -funroll-loops -march=native -I src -fopenmp contrib/legendre_rule_fast.c -o contrib/legendre_rule_fast.o
g++ -c -fPIC -O3 -funroll-loops -march=native -I src -fopenmp -DNEED_EXTERN_C -fopenmp src/finufft_c.cpp -o src/finufft_c.o
g++ -c -fPIC -O3 -funroll-loops -march=native -I src -fopenmp -DNEED_EXTERN_C -fopenmp fortran/finufft_f.cpp -o fortran/finufft_f.o
ar rcs lib-static/libfinufft.a src/spreadinterp.o src/utils.o src/finufft1d.o src/finufft2d.o src/finufft3d.o src/dirft1d.o src/dirft2d.o src/dirft3d.o src/common.o contrib/legendre_rule_fast.o src/finufft_c.o fortran/finufft_f.o
g++ -shared -fopenmp -lfftw3 -lm -lfftw3_threads src/spreadinterp.o src/utils.o src/finufft1d.o src/finufft2d.o src/finufft3d.o src/dirft1d.o src/dirft2d.o src/dirft3d.o src/common.o contrib/legendre_rule_fast.o src/finufft_c.o fortran/finufft_f.o -o lib/libfinufft.so
echo "lib-static/libfinufft.a and lib/libfinufft.so built, multithreaded versions"
lib-static/libfinufft.a and lib/libfinufft.so built, multithreaded versions
> pip install .
Processing /home/ludvigak/Dropbox/sfu-workspace/finufft
Requirement already satisfied: numpy in /home/ludvigak/anaconda2/lib/python2.7/site-packages (from finufftpy==1.0.1) (1.15.1)
Requirement already satisfied: pybind11>=2.2 in /home/ludvigak/anaconda2/lib/python2.7/site-packages (from finufftpy==1.0.1) (2.2.4)
Building wheels for collected packages: finufftpy
  Running setup.py bdist_wheel for finufftpy ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-RQcZ6F/wheels/b0/c6/54/bcdfb5074f313de4358eedbd1ad17e67ebd5aa7c0a2c1876aa
Successfully built finufftpy
Installing collected packages: finufftpy
  Found existing installation: finufftpy 1.0.1
    Uninstalling finufftpy-1.0.1:
      Successfully uninstalled finufftpy-1.0.1
Successfully installed finufftpy-1.0.1
> python -c 'import finufftpy'
> 
```

**Comment by ahbarnett** [comment]
Dear Robbie,
Sorry, Ludvig got there first. Yes, you must build the static lib before pip install. I'll update the doc to make this clearer. Best, Alex

**Comment by rbrook** [comment]
Thank you Alex and Ludvig!
Your direction was helpful. There were still minor bumps on the way but I
managed to install it.
I might open a pull-request if I encounter the same issues in the future
(1. setting *extra_link_args=['-L/usr/lib/x86_64-linux-gnu/']*  2. using
compile arg *-std=c++1y*).
Thank you so much for your replies!
Robbie
